services:
  app:
    build:
      context: .
      dockerfile: docker/8.2/Dockerfile
      args:
        WWWUSER: 1000
        WWWGROUP: 1000
    image: mini-crm-app
    container_name: mini-crm-app
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:stable-alpine
    container_name: mini-crm-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:8.1
    container_name: mini-crm-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mini_crm
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7
    container_name: mini-crm-redis
    ports:
      - "6379:6379"

volumes:
  dbdata:
